name: VAS Support
baseurl: /FeedWatch-Support-Site
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
exclude: [README.md, Gemfile, Gemfile.lock, scss]
timezone: America/Los_Angeles
sass:
  sass_dir: _sass
  style: :compressed