name: FeedWatch Support
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true
permalink: /:categories/:title
exclude: [README.md, Gemfile, Gemfile.lock, bower_components, bower.json, Gruntfile.js, package.json, node_modules, scss]
timezone: America/Los_Angeles
