name: FeedWatch Support
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true
permalink: /:categories/:title
exclude: [README.md, Gemfile, Gemfile.lock]

sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory
