name: FeedWatch Support
baseurl: /FeedWatch-Support-Site
markdown: kramdown
redcarpet:
  extensions: ["tables"]
highlighter: pygments
permalink: /:categories/:title
exclude: [README.md, Gemfile, Gemfile.lock, bower_components, bower.json, Gruntfile.js, package.json, node_modules, scss]
timezone: America/Los_Angeles
sass:
  sass_dir: _sass
  style: :compressed